version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "8888:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
